# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('AQI', models.IntegerField()),
                ('wuranwu', models.CharField(max_length=30)),
                ('PM25', models.IntegerField()),
                ('unit', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=30)),
                ('updated_time', models.DateTimeField()),
            ],
        ),
    ]
